# Generated by Django 4.2.2 on 2023-06-30 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='description',
            new_name='discount_percentage',
        ),
    ]
